repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml            # Validate YAML syntax
      - id: end-of-file-fixer     # Ensure newline at EOF
      - id: trailing-whitespace   # Strip trailing whitespace
      - id: check-merge-conflict  # Prevent commits with merge markers

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3

  # - repo: https://github.com/pycqa/pylint
  #   rev: v3.1.0
  #   hooks:
  #     - id: pylint
  #       name: pylint
  #       entry: pylint
  #       language: system
  #       types: [python]
  #       args: [repo_migrator]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: ["--py38-plus"]
