---
name: Docker Image Build

on:
  push:
    branches: ['main']
    paths:
      - 'Dockerfile' # Only trigger if Dockerfile is modified
  pull_request:
    branches: ['main']
    paths:
      - 'Dockerfile' # Only trigger if Dockerfile is modified
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile
